type MessageParams = Record<string, string | number>;

const englishMessages = {
  'extension.title': 'XRobot HPM Peripheral Config',
  'error.workspaceRequired': 'Open an HPM workspace folder first.',
  'error.commandExited': '{command} exited with {code}.',
  'notification.configRefreshed': 'HPM peripheral config refreshed: {file}',
  'notification.boardGlueGenerated': 'HPM board glue generated.',
  'notification.savedWithErrorsOne': 'Saved with {count} configuration error. Generate is blocked; see HPM Peripheral Config output.',
  'notification.savedWithErrorsMany': 'Saved with {count} configuration errors. Generate is blocked; see HPM Peripheral Config output.',
  'notification.configSavedChecked': 'HPM peripheral config saved and checked.',
  'notification.configGenerated': 'HPM peripheral config generated.',
  'error.pinmuxFileNotFound': 'HPM Pinmux file not found: {path}',
  'error.pinmuxExtensionMissing': 'HPMicro.hpm-pinmux-tool is not installed.',
  'error.projectGeneratorNotFound': 'Official HPM project generator not found under {path}.',

  'webview.title': 'XRobot HPM Peripheral Config',
  'webview.pinmuxFunctions': 'Pinmux functions',
  'webview.saveYaml': 'Save YAML',
  'webview.saveGenerate': 'Save + Generate',
  'webview.refreshHpmpc': 'Refresh from .hpmpc',
  'webview.openPinmux': 'Pinmux',
  'webview.openProjectGenerator': 'Proj Gen',
  'webview.noCommunicationPeripheral': 'Selected pinmux functions contain no communication peripheral; saved configurations are retained.',
  'webview.errorsBlockedOne': '{count} error - Generate blocked',
  'webview.errorsBlockedMany': '{count} errors - Generate blocked',
  'webview.validLimitationsOne': 'Configuration valid with {count} limitation',
  'webview.validLimitationsMany': 'Configuration valid with {count} limitations',
  'webview.configurationValid': 'Configuration valid',
  'webview.fieldAutoClock': 'Auto clock',
  'webview.fieldClockSource': 'Clock source',
  'webview.fieldClockDivider': 'Clock divider',
  'webview.peripheralClock': 'Peripheral clock: {hz} Hz',
  'webview.fieldBaudrate': 'Baudrate',
  'webview.fieldParity': 'Parity',
  'webview.optionParityNone': 'None',
  'webview.optionParityEven': 'Even',
  'webview.optionParityOdd': 'Odd',
  'webview.fieldDataBits': 'Data bits',
  'webview.fieldStopBits': 'Stop bits',
  'webview.fieldRxBufferSize': 'RX buffer size',
  'webview.fieldTxBufferSize': 'TX buffer size',
  'webview.fieldTxQueueSize': 'TX queue size',
  'webview.uartDmaAutomatic': 'DMA channels are allocated automatically and reserved by the HPM DMA manager.',
  'webview.fieldBusHz': 'Bus frequency',
  'webview.optionI2cStandard': '100 kHz (Standard)',
  'webview.optionI2cFast': '400 kHz (Fast)',
  'webview.optionI2cFastPlus': '1 MHz (Fast Plus)',
  'webview.fieldAddressMode': 'Address mode',
  'webview.option7BitMaster': '7-bit master',
  'webview.option10BitMaster': '10-bit master',
  'webview.i2cRuntimeDma': 'BLOCK uses polling; asynchronous operations allocate DMA at runtime.',
  'webview.fieldSclkHz': 'SCLK frequency',
  'webview.fieldBufferSize': 'Buffer size',
  'webview.fieldDoubleBuffer': 'Double buffer',
  'webview.fieldSpiMode': 'SPI mode',
  'webview.fieldClockPolarity': 'Clock polarity',
  'webview.optionPolarityLow': 'Low (idle low)',
  'webview.optionPolarityHigh': 'High (idle high)',
  'webview.fieldClockPhase': 'Clock phase',
  'webview.optionPhaseFirst': 'First edge sampling',
  'webview.optionPhaseSecond': 'Second edge sampling',
  'webview.fieldCsActiveLow': 'CS active low',
  'webview.hardwareCsFixed': 'Hardware CS is fixed active-low.',
  'webview.actualSclk': 'Actual SCLK: {hz} Hz / {prescaler}',
  'webview.fieldUseGpioCs': 'Use GPIO CS',
  'webview.fieldMode': 'Mode',
  'webview.fieldBitrate': 'Bitrate',
  'webview.fieldSamplePoint': 'Sample point',
  'webview.fieldQueueSize': 'Queue size',
  'webview.fieldLoopback': 'Loopback',
  'webview.fieldListenOnly': 'Listen only',
  'webview.fieldOneShot': 'One shot',
  'webview.fieldDataBitrate': 'Data bitrate',
  'webview.fieldDataSamplePoint': 'Data sample point',
  'webview.fieldBrs': 'BRS',
  'webview.fieldEsi': 'ESI',
  'webview.pins': 'Pins: {pins}',
  'webview.selectedOne': '{count} selected',
  'webview.selectedMany': '{count} selected',
  'webview.allFunctions': 'All functions',
  'webview.noPinmuxFunctions': 'No pinmux functions found.',
  'webview.enabledDetected': '{enabled} enabled / {detected} detected',
  'webview.none': 'None',
  'webview.noGroupPinmux': 'No {group} pinmux found.',

  'config.clockRange': '{instance}: peripheral clock must be between 1 Hz and 200000000 Hz.',
  'config.spiBufferSize': '{instance}: buffer_size must be a positive integer.',
  'config.spiDoubleBuffer': '{instance}: double_buffer requires buffer_size >= 2.',
  'config.spiSclkUnreachable': '{instance}: {requestedHz} Hz SCLK cannot be generated by the selected clock.',
  'config.spiHardwareCsActiveHigh': '{instance}: hardware chip-select polarity is fixed active-low; use GPIO CS for active-high.',
  'config.i2cBusRate': '{instance}: HPM LibXR I2C supports only 100000, 400000, or 1000000 Hz.',
  'config.i2cAddressMode': '{instance}: address_mode must be 7bit or 10bit.',
  'config.i2cTiming': '{instance}: {busHz} Hz timing cannot be represented at {clockHz} Hz.',
  'config.uartBaudrate': '{instance}: baudrate {baudrate} is not reachable within the HPM SDK 3% tolerance.',
  'config.uartRxBuffer': '{instance}: rx_buffer_size must be a positive integer.',
  'config.uartTxBuffer': '{instance}: tx_buffer_size must be an integer of at least 2 bytes.',
  'config.uartTxQueue': '{instance}: tx_queue_size must be a positive integer.',
  'config.uartParity': '{instance}: parity must be NO_PARITY, EVEN, or ODD.',
  'config.uartDataBits': '{instance}: data_bits must be between 5 and 8.',
  'config.uartStopBits': '{instance}: stop_bits must be 1 or 2.',
  'config.canMode': '{instance}: mode must be can or fdcan.',
  'config.canNominalTiming': '{instance}: nominal bitrate/sample point is not reachable at {clockHz} Hz.',
  'config.canDataTiming': '{instance}: data bitrate/sample point is not reachable at {clockHz} Hz.',
  'config.canQueue': '{instance}: queue_size must be a positive integer.',
  'config.canModeConflict': '{instance}: loopback and listen_only cannot be enabled together on the HPM backend.',
  'config.gpioCsPolarity': 'GPIO chip-select polarity must match because this board uses one BOARD_SPI_CS_ACTIVE_LEVEL macro.',
  'config.gpioCsCount': 'This board exposes one global GPIO SPI chip-select; enable GPIO CS for at most one SPI instance.',
  'config.validationFailed': 'Peripheral configuration check failed:',
  'config.clockTreeLimited': '{board}: only the 24 MHz oscillator is modeled; PLL clock-tree auto selection is unavailable.',
  'config.spiSclkAdjusted': '{instance}: requested {requestedHz} Hz, actual SCLK is {actualHz} Hz.',
  'config.spiHardwareCsFixed': '{instance}: hardware chip-select is fixed active-low by the HPM SPI peripheral.',

  'generator.clockFunctionMissing': '{functionName} is missing from board.c; cannot apply the {base} clock.',
  'generator.gpioCsHelpersMissing': 'GPIO SPI chip-select requires BOARD_SPI_CS_PIN, BOARD_SPI_CS_ACTIVE_LEVEL, and board_write_spi_cs().',
  'generator.canMarkerMissing': 'Existing CAN board helpers have no HPM Peripheral Config marker; refusing to overwrite them.',
  'project.hpmpcNotFound': 'No .hpmpc file found in the workspace.',
  'project.boardFilesNotFound': 'No HPM board.c/board.h directory found.',
  'hpmpc.notObject': 'HPM configuration is not a JSON object.',
  'hpmpc.signedCopyInvalid': 'The HPM signed working copy is invalid.',
  'hpmpc.signedCopyNotFound': 'No valid signed .hpmpc working copy was found under the sibling .xrobot-local directory.',
} as const;

type MessageKey = keyof typeof englishMessages;

const simplifiedChineseMessages: Record<MessageKey, string> = {
  'extension.title': 'XRobot HPM 外设配置',
  'error.workspaceRequired': '请先打开一个 HPM 工作区文件夹。',
  'error.commandExited': '{command} 已退出，退出码为 {code}。',
  'notification.configRefreshed': 'HPM 外设配置已刷新：{file}',
  'notification.boardGlueGenerated': 'HPM 板级适配代码已生成。',
  'notification.savedWithErrorsOne': '配置已保存，但存在 {count} 个配置错误。已阻止生成，请查看 HPM 外设配置输出。',
  'notification.savedWithErrorsMany': '配置已保存，但存在 {count} 个配置错误。已阻止生成，请查看 HPM 外设配置输出。',
  'notification.configSavedChecked': 'HPM 外设配置已保存并通过检查。',
  'notification.configGenerated': 'HPM 外设配置已生成。',
  'error.pinmuxFileNotFound': '未找到 HPM Pinmux 文件：{path}',
  'error.pinmuxExtensionMissing': '尚未安装 HPMicro.hpm-pinmux-tool。',
  'error.projectGeneratorNotFound': '在 {path} 下未找到 HPM 官方工程生成器。',

  'webview.title': 'XRobot HPM 外设配置',
  'webview.pinmuxFunctions': 'Pinmux 函数',
  'webview.saveYaml': '保存 YAML',
  'webview.saveGenerate': '保存并生成',
  'webview.refreshHpmpc': '从 .hpmpc 刷新',
  'webview.openPinmux': 'Pinmux 配置',
  'webview.openProjectGenerator': '工程生成器',
  'webview.noCommunicationPeripheral': '选中的 Pinmux 函数不包含通信外设；已保存的外设配置会继续保留。',
  'webview.errorsBlockedOne': '{count} 个错误 - 已阻止生成',
  'webview.errorsBlockedMany': '{count} 个错误 - 已阻止生成',
  'webview.validLimitationsOne': '配置有效，但有 {count} 项限制',
  'webview.validLimitationsMany': '配置有效，但有 {count} 项限制',
  'webview.configurationValid': '配置有效',
  'webview.fieldAutoClock': '自动配置时钟',
  'webview.fieldClockSource': '时钟源',
  'webview.fieldClockDivider': '时钟分频',
  'webview.peripheralClock': '外设时钟：{hz} Hz',
  'webview.fieldBaudrate': '波特率',
  'webview.fieldParity': '校验位',
  'webview.optionParityNone': '无校验',
  'webview.optionParityEven': '偶校验',
  'webview.optionParityOdd': '奇校验',
  'webview.fieldDataBits': '数据位',
  'webview.fieldStopBits': '停止位',
  'webview.fieldRxBufferSize': '接收缓冲区大小',
  'webview.fieldTxBufferSize': '发送缓冲区大小',
  'webview.fieldTxQueueSize': '发送队列大小',
  'webview.uartDmaAutomatic': 'DMA 通道由 HPM DMA 管理器自动分配并保留。',
  'webview.fieldBusHz': '总线频率',
  'webview.optionI2cStandard': '100 kHz（标准模式）',
  'webview.optionI2cFast': '400 kHz（快速模式）',
  'webview.optionI2cFastPlus': '1 MHz（快速增强模式）',
  'webview.fieldAddressMode': '地址模式',
  'webview.option7BitMaster': '7 位主机',
  'webview.option10BitMaster': '10 位主机',
  'webview.i2cRuntimeDma': 'BLOCK 操作使用轮询；异步操作会在运行时分配 DMA。',
  'webview.fieldSclkHz': 'SCLK 频率',
  'webview.fieldBufferSize': '缓冲区大小',
  'webview.fieldDoubleBuffer': '双缓冲',
  'webview.fieldSpiMode': 'SPI 模式',
  'webview.fieldClockPolarity': '时钟极性',
  'webview.optionPolarityLow': '低电平（空闲时为低）',
  'webview.optionPolarityHigh': '高电平（空闲时为高）',
  'webview.fieldClockPhase': '时钟相位',
  'webview.optionPhaseFirst': '第一个边沿采样',
  'webview.optionPhaseSecond': '第二个边沿采样',
  'webview.fieldCsActiveLow': 'CS 低电平有效',
  'webview.hardwareCsFixed': '硬件 CS 固定为低电平有效。',
  'webview.actualSclk': '实际 SCLK：{hz} Hz / {prescaler}',
  'webview.fieldUseGpioCs': '使用 GPIO 片选',
  'webview.fieldMode': '模式',
  'webview.fieldBitrate': '比特率',
  'webview.fieldSamplePoint': '采样点',
  'webview.fieldQueueSize': '队列大小',
  'webview.fieldLoopback': '环回模式',
  'webview.fieldListenOnly': '只听模式',
  'webview.fieldOneShot': '单次发送',
  'webview.fieldDataBitrate': '数据段比特率',
  'webview.fieldDataSamplePoint': '数据段采样点',
  'webview.fieldBrs': 'BRS',
  'webview.fieldEsi': 'ESI',
  'webview.pins': '引脚：{pins}',
  'webview.selectedOne': '已选择 {count} 个',
  'webview.selectedMany': '已选择 {count} 个',
  'webview.allFunctions': '全部函数',
  'webview.noPinmuxFunctions': '未找到 Pinmux 函数。',
  'webview.enabledDetected': '已启用 {enabled} 个 / 检测到 {detected} 个',
  'webview.none': '无',
  'webview.noGroupPinmux': '未找到 {group} Pinmux。',

  'config.clockRange': '{instance}：外设时钟必须在 1 Hz 到 200000000 Hz 之间。',
  'config.spiBufferSize': '{instance}：buffer_size 必须为正整数。',
  'config.spiDoubleBuffer': '{instance}：启用 double_buffer 时 buffer_size 必须大于等于 2。',
  'config.spiSclkUnreachable': '{instance}：所选时钟无法生成 {requestedHz} Hz 的 SCLK。',
  'config.spiHardwareCsActiveHigh': '{instance}：硬件片选固定为低电平有效；高电平有效时请使用 GPIO CS。',
  'config.i2cBusRate': '{instance}：HPM LibXR I2C 仅支持 100000、400000 或 1000000 Hz。',
  'config.i2cAddressMode': '{instance}：address_mode 必须为 7bit 或 10bit。',
  'config.i2cTiming': '{instance}：{clockHz} Hz 外设时钟无法表示 {busHz} Hz 的时序。',
  'config.uartBaudrate': '{instance}：波特率 {baudrate} 无法满足 HPM SDK 的 3% 误差要求。',
  'config.uartRxBuffer': '{instance}：rx_buffer_size 必须为正整数。',
  'config.uartTxBuffer': '{instance}：tx_buffer_size 必须为不小于 2 字节的整数。',
  'config.uartTxQueue': '{instance}：tx_queue_size 必须为正整数。',
  'config.uartParity': '{instance}：parity 必须为 NO_PARITY、EVEN 或 ODD。',
  'config.uartDataBits': '{instance}：data_bits 必须在 5 到 8 之间。',
  'config.uartStopBits': '{instance}：stop_bits 必须为 1 或 2。',
  'config.canMode': '{instance}：mode 必须为 can 或 fdcan。',
  'config.canNominalTiming': '{instance}：在 {clockHz} Hz 时钟下无法实现标称比特率/采样点。',
  'config.canDataTiming': '{instance}：在 {clockHz} Hz 时钟下无法实现数据段比特率/采样点。',
  'config.canQueue': '{instance}：queue_size 必须为正整数。',
  'config.canModeConflict': '{instance}：HPM 后端不能同时启用 loopback 和 listen_only。',
  'config.gpioCsPolarity': 'GPIO 片选极性必须一致，因为此板卡共用一个 BOARD_SPI_CS_ACTIVE_LEVEL 宏。',
  'config.gpioCsCount': '此板卡只提供一个全局 GPIO SPI 片选；最多只能为一个 SPI 实例启用 GPIO CS。',
  'config.validationFailed': '外设配置检查失败：',
  'config.clockTreeLimited': '{board}：当前只建模了 24 MHz 晶振，无法自动选择 PLL 时钟树。',
  'config.spiSclkAdjusted': '{instance}：请求 {requestedHz} Hz，实际 SCLK 为 {actualHz} Hz。',
  'config.spiHardwareCsFixed': '{instance}：HPM SPI 外设的硬件片选固定为低电平有效。',

  'generator.clockFunctionMissing': 'board.c 中缺少 {functionName}，无法应用 {base} 时钟。',
  'generator.gpioCsHelpersMissing': 'GPIO SPI 片选需要 BOARD_SPI_CS_PIN、BOARD_SPI_CS_ACTIVE_LEVEL 和 board_write_spi_cs()。',
  'generator.canMarkerMissing': '现有 CAN 板级辅助函数没有 HPM Peripheral Config 标记，已拒绝覆盖。',
  'project.hpmpcNotFound': '工作区中未找到 .hpmpc 文件。',
  'project.boardFilesNotFound': '未找到包含 HPM board.c/board.h 的目录。',
  'hpmpc.notObject': 'HPM 配置不是 JSON 对象。',
  'hpmpc.signedCopyInvalid': 'HPM 签名工作副本无效。',
  'hpmpc.signedCopyNotFound': '相邻的 .xrobot-local 目录中没有有效的已签名 .hpmpc 工作副本。',
};

export type Locale = 'en' | 'zh-cn';

let activeLocale: Locale = 'en';

function resolveLocale(language: string): Locale {
  const normalized = language.trim().toLowerCase().replace(/_/g, '-');
  return normalized === 'zh' || normalized === 'zh-cn' || normalized.startsWith('zh-hans')
    ? 'zh-cn'
    : 'en';
}

function catalog(locale: Locale): Record<MessageKey, string> {
  return locale === 'zh-cn' ? simplifiedChineseMessages : englishMessages;
}

export function setLocale(language: string): void {
  activeLocale = resolveLocale(language);
}

export function currentLocale(): Locale {
  return activeLocale;
}

export function messagesForLocale(language: string): Readonly<Record<MessageKey, string>> {
  return catalog(resolveLocale(language));
}

export function t(key: MessageKey, params: MessageParams = {}): string {
  const selected = catalog(activeLocale);
  const template = selected[key] ?? englishMessages[key] ?? key;
  return template.replace(/\{([A-Za-z][A-Za-z0-9_]*)\}/g, (placeholder, name: string) => (
    Object.prototype.hasOwnProperty.call(params, name) ? String(params[name]) : placeholder
  ));
}

export function webviewMessages(): Record<string, string> {
  const selected = catalog(activeLocale);
  return Object.fromEntries(
    Object.entries(selected)
      .filter(([key]) => key.startsWith('webview.'))
      .map(([key, value]) => [key.slice('webview.'.length), value]),
  );
}
